import mongoose from "mongoose";

const AddressSnapshotSchema = new mongoose.Schema(
  {
    fullName: { type: String, default: "", trim: true },
    phone: { type: String, default: "", trim: true },
    line1: { type: String, default: "", trim: true },
    line2: { type: String, default: "", trim: true },
    city: { type: String, default: "", trim: true },
    state: { type: String, default: "", trim: true },
    postalCode: { type: String, default: "", trim: true },
    country: { type: String, default: "", trim: true },
  },
  { _id: false }
);

const PricingSnapshotSchema = new mongoose.Schema(
  {
    version: { type: Number, default: 1, min: 1 },
    currency: { type: String, default: "INR", trim: true },
    pricingRuleVersion: { type: Number, default: 1, min: 1 },
    priceIncludesTax: { type: Boolean, default: true },
    taxMode: { type: String, default: "inclusive", trim: true },
    subtotalBeforeCoupon: { type: Number, default: 0, min: 0 },
    catalogDiscountTotal: { type: Number, default: 0, min: 0 },
    couponDiscountTotal: { type: Number, default: 0, min: 0 },
    discountTotal: { type: Number, default: 0, min: 0 },
    discountedMerchandiseTotalBeforeCoupon: { type: Number, default: 0, min: 0 },
    discountedMerchandiseTotal: { type: Number, default: 0, min: 0 },
    taxableBaseTotal: { type: Number, default: 0, min: 0 },
    shippingTotal: { type: Number, default: 0, min: 0 },
    taxTotal: { type: Number, default: 0, min: 0 },
    includedTaxTotal: { type: Number, default: 0, min: 0 },
    shippingTaxTotal: { type: Number, default: 0, min: 0 },
    grandTotal: { type: Number, default: 0, min: 0 },
    payableTotal: { type: Number, default: 0, min: 0 },
    allocationMode: { type: String, default: "order_level_only", trim: true },
    taxRatesUsed: { type: [Number], default: [] },
    shippingRule: {
      key: { type: String, default: "flat_zero", trim: true },
      label: { type: String, default: "", trim: true },
      amount: { type: Number, default: 0, min: 0 },
      standardCharge: { type: Number, default: 0, min: 0 },
      freeThreshold: { type: Number, default: 0, min: 0 },
      eligibleSubtotal: { type: Number, default: 0, min: 0 },
      shippingTaxMode: { type: String, default: "not_calculated_v1", trim: true },
      shippingTaxTotal: { type: Number, default: 0, min: 0 },
    },
    taxRule: {
      key: { type: String, default: "flat_zero", trim: true },
      label: { type: String, default: "", trim: true },
      defaultRate: { type: Number, default: 0, min: 0 },
      ratePercent: { type: Number, default: 0, min: 0 },
      amount: { type: Number, default: 0, min: 0 },
      taxMode: { type: String, default: "inclusive", trim: true },
    },
    calculatedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

// This schema remains a transitional order read-model until checkout is moved
// into a dedicated order-svc. The commercial fields already use immutable
// snapshots so future order ownership can migrate without changing the contract.
const CustomerOrderItemSchema = new mongoose.Schema(
  {
    lineId: {
      type: String,
      default: () => new mongoose.Types.ObjectId().toString(),
      trim: true,
    },
    productId: { type: mongoose.Schema.Types.ObjectId, default: null },
    variantId: { type: mongoose.Schema.Types.ObjectId, default: null },
    categoryId: { type: mongoose.Schema.Types.ObjectId, default: null },
    categoryLabel: { type: String, default: "", trim: true },
    stockKey: { type: String, default: "", trim: true },
    slug: { type: String, default: "" },
    title: { type: String, required: true, trim: true },
    imageUrl: { type: String, default: "" },
    quantity: { type: Number, default: 1, min: 1 },
    fulfillmentStatus: { type: String, default: "RESERVED", trim: true },
    physicalOwner: { type: String, default: "WAREHOUSE", trim: true },
    cancellationSource: { type: String, default: "", trim: true },
    cancellationReason: { type: String, default: "", trim: true },
    packageVerificationStatus: { type: String, default: "PENDING", trim: true },
    labelStatus: { type: String, default: "NOT_PRINTED", trim: true },
    labelReprintCount: { type: Number, default: 0, min: 0 },
    labelReprintReason: { type: String, default: "", trim: true },
    courierName: { type: String, default: "", trim: true },
    outboundTrackingNumber: { type: String, default: "", trim: true },
    collectionTrackingNumber: { type: String, default: "", trim: true },
    targetCompletionDate: { type: Date, default: null },
    laneAssignedAt: { type: Date, default: null },
    lastActionedAt: { type: Date, default: null },
    slaStatus: { type: String, default: "ON_TRACK", trim: true },
    cancelRequestedAt: { type: Date, default: null },
    pickedAt: { type: Date, default: null },
    pickedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    handedToPackagingAt: { type: Date, default: null },
    packedAt: { type: Date, default: null },
    packedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    packagingReceivedAt: { type: Date, default: null },
    packagingReceivedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    packagingStartedAt: { type: Date, default: null },
    packagingStartedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    packageVerifiedAt: { type: Date, default: null },
    packageVerifiedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    labelPrintedAt: { type: Date, default: null },
    labelPrintedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    handedToShippingAt: { type: Date, default: null },
    shippingReceivedAt: { type: Date, default: null },
    shippingReceivedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    shippingStartedAt: { type: Date, default: null },
    shippingStartedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    courierAssignedAt: { type: Date, default: null },
    courierAssignedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    trackingNumberEnteredAt: { type: Date, default: null },
    trackingNumberEnteredBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    unpackedAt: { type: Date, default: null },
    shippedAt: { type: Date, default: null },
    shippedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    deliveredAt: { type: Date, default: null },
    deliveredBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    cancelledAt: { type: Date, default: null },
    adminCancelledAt: { type: Date, default: null },
    handedToCancellationAt: { type: Date, default: null },
    cancellationReceivedAt: { type: Date, default: null },
    cancellationReceivedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    cancellationClosedAt: { type: Date, default: null },
    cancellationClosedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    returnRequestedAt: { type: Date, default: null },
    collectionScheduledAt: { type: Date, default: null },
    returnReceivedAt: { type: Date, default: null },
    returnReceivedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    inventoryAcceptedAt: { type: Date, default: null },
    inventoryAcceptedBy: { type: mongoose.Schema.Types.ObjectId, default: null, ref: "User" },
    refundCompletedAt: { type: Date, default: null },
    currency: { type: String, default: "INR", trim: true },
    listUnitPrice: { type: Number, default: 0, min: 0 },
    catalogDiscountType: { type: String, default: "none", trim: true },
    catalogDiscountValue: { type: Number, default: 0, min: 0 },
    catalogDiscountLabel: { type: String, default: "", trim: true },
    catalogDiscountAmount: { type: Number, default: 0, min: 0 },
    promoDiscountType: { type: String, default: "none", trim: true },
    promoDiscountValue: { type: Number, default: 0, min: 0 },
    promoDiscountLabel: { type: String, default: "", trim: true },
    promoDiscountAmount: { type: Number, default: 0, min: 0 },
    taxRate: { type: Number, default: 0.05, min: 0 },
    priceIncludesTax: { type: Boolean, default: true },
    finalUnitPrice: { type: Number, default: 0, min: 0 },
    lineSubtotal: { type: Number, default: 0, min: 0 },
    lineTaxableBaseTotal: { type: Number, default: 0, min: 0 },
    lineTaxTotal: { type: Number, default: 0, min: 0 },
    lineShippingTotal: { type: Number, default: 0, min: 0 },
    lineDiscountTotal: { type: Number, default: 0, min: 0 },
    lineGrandTotal: { type: Number, default: 0, min: 0 },
    unitPrice: { type: Number, default: 0, min: 0 },
    lineTotal: { type: Number, default: 0, min: 0 },
  },
  { _id: false }
);

const CustomerOrderSchema = new mongoose.Schema(
  {
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "StorefrontCustomer",
      required: true,
      index: true,
    },
    status: { type: String, default: "placed", trim: true },
    paymentStatus: { type: String, default: "pending", trim: true },
    fulfillmentStatus: { type: String, default: "pending", trim: true },
    currency: { type: String, default: "INR", trim: true },
    pricingVersion: { type: Number, default: 1, min: 1 },
    couponCode: { type: String, default: "", trim: true },
    couponDiscountTotal: { type: Number, default: 0, min: 0 },
    couponAppliedAmount: { type: Number, default: 0, min: 0 },
    couponForfeitedAmount: { type: Number, default: 0, min: 0 },
    subtotal: { type: Number, default: 0, min: 0 },
    discountTotal: { type: Number, default: 0, min: 0 },
    shippingTotal: { type: Number, default: 0, min: 0 },
    taxableBaseTotal: { type: Number, default: 0, min: 0 },
    taxTotal: { type: Number, default: 0, min: 0 },
    grandTotal: { type: Number, default: 0, min: 0 },
    total: { type: Number, default: 0, min: 0 },
    itemCount: { type: Number, default: 0, min: 0 },
    displayId: {
      type: String,
      default: () => `ORD-${new mongoose.Types.ObjectId().toString().slice(-8).toUpperCase()}`,
      trim: true,
      index: true,
    },
    paymentReference: { type: String, default: "", trim: true },
    pricingSnapshot: { type: PricingSnapshotSchema, default: () => ({}) },
    addressSnapshot: { type: AddressSnapshotSchema, default: () => ({}) },
    items: { type: [CustomerOrderItemSchema], default: [] },
    placedAt: { type: Date, default: Date.now },
  },
  {
    timestamps: true,
    collection: "storefront_customer_orders",
  }
);

CustomerOrderSchema.index({ customer: 1, placedAt: -1 });

export default mongoose.model("StorefrontCustomerOrder", CustomerOrderSchema);
