module.exports = {
  apps: [
    {
      name: "sacom-auth",
      cwd: "./auth-svc",
      script: "npm",
      args: "start",
      env: { NODE_ENV: "production", HOST: "127.0.0.1", PORT: "4443", HTTPS_PORT: "4443" },
      autorestart: true,
      max_memory_restart: "400M",
    },
    {
      name: "sacom-catalog",
      cwd: "./catalog-svc",
      script: "npm",
      args: "start",
      env: { NODE_ENV: "production", HOST: "127.0.0.1", PORT: "4444", HTTPS_PORT: "4444" },
      autorestart: true,
      max_memory_restart: "300M",
    },
    {
      name: "sacom-product",
      cwd: "./product-svc",
      script: "npm",
      args: "start",
      env: { NODE_ENV: "production", HOST: "127.0.0.1", PORT: "4445", HTTPS_PORT: "4445" },
      autorestart: true,
      max_memory_restart: "500M",
    },
    {
      name: "sacom-gateway",
      cwd: "./gateway-svc",
      script: "npm",
      args: "start",
      env: { NODE_ENV: "production", HOST: "127.0.0.1", PORT: "4000" },
      autorestart: true,
      max_memory_restart: "300M",
    },
    {
      name: "sacom-admin",
      cwd: "./admin-portal",
      script: "npm",
      args: "start -- -p 3000 -H 127.0.0.1",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "500M",
    },
    {
      name: "sacom-storefront",
      cwd: "./siri-frontend-simple-proxy-v2",
      script: "npm",
      args: "start -- -p 3001 -H 127.0.0.1",
      env: { NODE_ENV: "production" },
      autorestart: true,
      max_memory_restart: "500M",
    },
  ],
};
