export const STOREFRONT_STRINGS = {
  brand: {
    name: "Siri Collections",
    fallbackCategoryLabel: "Collection",
    fallbackCategorySlug: "collection",
  },
  navigation: {
    account: {
      welcome: "Welcome",
      welcomeBack: "Hello",
      guestSubtitle: "To access account and manage orders",
      loginSignup: "Login / Signup",
      logout: "Logout",
      orders: "Orders",
      wishlist: "Wishlist",
      savedAddresses: "Saved Addresses",
      customerAccount: "Account",
    },
    cart: {
      unavailable: "Cart is temporarily unavailable",
    },
  },
  home: {
    loading: "Loading storefront…",
    heroEyebrow: "Category First Luxury Storefront",
    heroTitle: "Celebrate every drape with a commerce experience built like Siri Collections.",
    heroCopy:
      "Browse blouse stories first, discover upcoming categories as they launch, and keep your cart ready for a smoother checkout the moment customer login arrives.",
    browseCategories: "Browse Categories",
    exploreCategories: "Explore Categories",
    browseByCategory: "Browse by Category",
    allCollectionsStayVisible: "All Collections Stay Visible",
    categoryTreeCopy:
      "Categories come from the active category tree. Blouse, Mangalsutra, and Printed Sarees are live now; the rest stay published as coming-soon destinations.",
    liveInventory: "Live Inventory",
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    viewAll: "View All",
    selectedCollection: "Selected Collection",
    liveRailUnavailable:
      "The live blouse rail is temporarily unavailable while the storefront backend recovers.",
    liveRailComingSoonTitle: "The live blouse rail will appear here when merchandise is available.",
    liveRailComingSoonCopy:
      "If the primary live category has no products available yet, the storefront stays intact and waits for the catalog to go live.",
    liveCategoryCopy: (label: string) =>
      `Browse the live ${label.toLowerCase()} catalog with full listing and product detail support.`,
    upcomingCategoryCopy:
      "This category remains visible in the menu and opens a branded coming-soon page until merchandise is launched.",
  },
  category: {
    loading: "Loading category…",
    collection: "Collection",
    filters: "Filters",
    price: "Price",
    loadingMore: "Loading more products...",
    noFilters: "No filters are configured for this live category yet.",
    notFound: "Not Found",
    notFoundTitle: "This category does not exist.",
    notFoundCopy:
      "Choose another collection from the storefront menu. Category pages are generated from the active category tree.",
    comingSoon: "Coming Soon",
    comingSoonTitle: (heading: string) => `${heading} is visible in categories and preparing to launch.`,
    comingSoonCopy:
      "The category page is intentionally published before merchandise arrives. Live categories fetch products automatically once they are launched.",
    listingUnavailable:
      "The live category listing is temporarily unavailable. Category routing is still working, but the catalog data could not be loaded.",
    emptyListingTitle: (heading: string) => `${heading} will appear here soon.`,
    emptyListingCopy:
      "This route is live. Once products are active in the catalog, this listing automatically switches from placeholder state to a full merchandise grid.",
    searchPlaceholder: (label: string) => `Search ${label.toLowerCase()}`,
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToHome: "Back to Home",
  },
  productCard: {
    emptyImage: "Coming Soon",
    fallbackDescription: "Curated collection",
    viewDetails: "View Details",
  },
  product: {
    loading: "Loading product…",
    notFound: "Product not found.",
    variantFallback: "Variant",
    descriptionFallback: "Description coming soon.",
    dryCleanFallback: "Dry clean guidance will be added shortly.",
    shippingFallback: "Shipping details coming soon.",
    returnsFallback: "Return and exchange details coming soon.",
    returnableYes: "Yes",
    returnableNo: "No",
    inStock: "In stock",
    futureLaunchVisible: "Made visible for future launch",
    selectVariant: "Select Variant",
    selectSize: "Select Size",
    fallbackSize: "Size",
    addToCart: "Add to Cart",
    saveToWishlist: "Save to Wishlist",
    wishlistSaved: "Saved to wishlist",
    wishlistFailed: "Unable to save wishlist item",
    tabs: {
      description: "Description",
      dryClean: "Dry Clean",
      shipping: "Shipping",
      returns: "Return & Exchange",
    },
    recentlyViewed: "Recently Viewed",
    sameCategoryInspiration: "Same Category Inspiration",
    recentlyViewedEmpty:
      "Start browsing this category to build your recently viewed rail.",
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToCategory: (slug: string) => `Back to ${slug}`,
  },
  account: {
    auth: {
      kicker: "Customer Account",
      loginTitle: "Login to Siri",
      signupTitle: "Create your Siri account",
      subtitle:
        "Save addresses, manage wishlist items, and track customer orders from one account.",
      tabs: {
        login: "Login",
        signup: "Signup",
      },
      fields: {
        name: "Name",
        phone: "Phone",
        email: "Email",
        password: "Password",
      },
      submit: {
        busy: "Please wait...",
        login: "Login",
        signup: "Create Account",
      },
      fallbackError: "Unable to continue",
    },
    shell: {
      title: "Account",
    },
    orders: {
      title: "Orders",
      subtitle: "Track your recent purchases and view line-item details.",
      emptyTitle: "No orders yet.",
      emptyCopy:
        "Your placed orders will appear here once customer checkout starts creating order history.",
      fallbackError: "Unable to load orders",
      status: "Status",
      qty: "Qty",
      orderPrefix: "Order #",
    },
    wishlist: {
      title: "Wishlist",
      subtitle: "Saved products stay ready here while you browse the catalog.",
      emptyTitle: "Your wishlist is empty.",
      emptyCopy: "Add products from the product detail page to keep them here.",
      remove: "Remove",
      fallbackError: "Unable to load wishlist",
    },
    addresses: {
      title: "Saved Addresses",
      subtitle: "Save delivery addresses for a faster checkout when customer ordering is enabled.",
      fallbackError: "Unable to load addresses",
      saveFailed: "Unable to save address",
      emptyTitle: "No saved addresses yet.",
      emptyCopy: "Add your first address to make future checkout faster.",
      defaultBadge: "Default",
      defaultCheckbox: "Set as default address",
      actions: {
        save: "Save Address",
        update: "Update Address",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
      },
      fields: {
        fullName: "Full Name",
        phone: "Phone",
        line1: "Address Line 1",
        line2: "Address Line 2",
        city: "City",
        state: "State",
        postalCode: "Postal Code",
        country: "Country",
      },
    },
  },
} as const;
