export const STOREFRONT_STRINGS = {
  brand: {
    name: "పూజిత",
    tagline: "Sarees, Jewellery & Curated Collections",
    homeAriaLabel: "పూజిత home",
    fallbackCategoryLabel: "Collection",
    fallbackCategorySlug: "collection",
  },
  navigation: {
    promo: "Free Shipping Above ₹2500 • GST-Inclusive Pricing • Secure Checkout",
    home: "Home",
    newArrivals: "New Arrivals",
    menu: "Menu",
    closeMenu: "Close Menu",
    browseStore: "Browse Store",
    cartLabel: "Cart",
    account: {
      welcome: "Welcome",
      welcomeBack: "Hello",
      guestSubtitle: "To access account and manage orders",
      loginSignup: "Login / Signup",
      logout: "Logout",
      orders: "Orders",
      coupons: "Coupons",
      wishlist: "Wishlist",
      savedAddresses: "Saved Addresses",
      customerAccount: "Account",
    },
    cart: {
      unavailable: "Cart is temporarily unavailable",
    },
  },
  home: {
    loading: "Loading storefront…",
    heroEyebrow: "Fresh arrivals, festive picks, everyday elegance",
    heroTitle: "Celebrate every occasion with handpicked sarees.",
    heroCopy:
      "Fresh arrivals, festive picks, and everyday elegance.",
    heroPrimaryCta: "Shop New Arrivals",
    heroSecondaryCta: "Explore Sarees",
    heroProductBadge: "Boutique Pick",
    browseCategories: "Browse Collections",
    exploreCategories: "Explore Collections",
    browseByCategory: "Shop by Collection",
    allCollectionsStayVisible: "Collections to Start Your Shopping Journey",
    categoryTreeCopy:
      "Browse the live category tree through sarees, jewellery, blouses, dupattas, and sale edits without losing sight of the products.",
    newArrivals: "New Arrivals",
    newArrivalsTitle: "Fresh Picks to Shop Now",
    newArrivalsCopy:
      "Recently added styles from the live catalog, ready to shop now.",
    featuredCollections: "Featured Collections",
    featuredCollectionsTitle: "Shop the Collection",
    featuredCollectionsCopy:
      "Browse curated collection edits powered by the live category hierarchy and active products.",
    featuredEditKicker: "Featured Edit",
    featuredEditTitle: "Sarees and bestselling boutique picks",
    featuredEditCopy:
      "Handpicked drapes, festive favourites, and standout styles from the latest live assortment.",
    collectionTilesKicker: "Shop by Collection",
    collectionTilesTitle: "Find the pieces you came for.",
    collectionTilesCopy:
      "Move from sarees to jewellery, blouses, dupattas, and sale edits in just a few taps.",
    saleKicker: "Offer Edit",
    saleTitle: "Sale picks and value finds",
    saleCopy:
      "Browse offer-led styles and Half Price Store collections while they are still live.",
    styleEditKicker: "Complete the Look",
    styleEditTitle: "Jewellery, blouses, and finishing touches",
    styleEditCopy:
      "Pair your sarees with matching accessories and styling pieces from live collections.",
    viewAll: "View All",
    browseCollection: (label: string) => `Browse ${label}`,
    shopCollection: (label: string) => `Shop ${label}`,
    categoryCardCopy:
      "Browse the collection and shop active styles across the live category branch.",
    railUnavailable:
      "This collection rail is temporarily unavailable while the storefront backend recovers.",
    railComingSoonTitle: (label: string) => `${label} will appear here soon.`,
    railComingSoonCopy:
      "This collection will appear automatically as soon as active products are added to the live catalog.",
    valuesEyebrow: "Shop with Confidence",
    valuesTitle: "Thoughtful details for a smoother boutique experience.",
    values: [
      {
        title: "GST-Inclusive Pricing",
        copy: "Clear product pricing with GST-inclusive wording carried through the storefront.",
      },
      {
        title: "Secure Checkout",
        copy: "Move from product discovery to cart and checkout with a simple, secure shopping flow.",
      },
      {
        title: "Exchange & Help Support",
        copy: "Account tools stay ready for order tracking, wishlist use, saved addresses, and post-purchase help.",
      },
      {
        title: "Shipping Benefits",
        copy: "Delivery-friendly shopping with a free-shipping threshold highlighted right from the header.",
      },
    ],
  },
  category: {
    loading: "Loading category…",
    collection: "Collection",
    subcategories: "Shop by Subcategory",
    subcategoriesTitle: "Explore the Collection",
    subcategoriesCopy:
      "Browse a focused subcategory or continue shopping the full collection across live products in this branch.",
    viewSubcategory: (label: string) => `View ${label}`,
    filters: "Filters",
    filterButton: (count: number) => (count ? `Filters (${count})` : "Filters"),
    filterSheetTitle: "Refine Collection",
    applyFilters: "Apply Filters",
    clearFilters: "Clear All",
    closeFilters: "Close",
    activeFilters: "Active Filters",
    resultsCount: (count: number) => `${count} products`,
    price: "Price",
    loadingMore: "Loading more products...",
    noFilters: "No filters are configured for this collection yet.",
    notFound: "Not Found",
    notFoundTitle: "This category does not exist.",
    notFoundCopy:
      "Choose another collection from the storefront menu. Category pages are generated from the active category tree.",
    comingSoon: "Coming Soon",
    comingSoonTitle: (heading: string) => `${heading} is visible in collections and preparing to launch.`,
    comingSoonCopy:
      "This collection exists in the storefront taxonomy before merchandise is ready. The page will automatically switch to a full listing as products arrive.",
    listingUnavailable:
      "The collection listing is temporarily unavailable. Category routing is still working, but the catalog data could not be loaded.",
    emptyListingTitle: (heading: string) => `${heading} will appear here soon.`,
    emptyListingCopy:
      "This collection route is already active. As soon as products are added anywhere inside this branch of the category tree, the page will switch to a full merchandise grid.",
    searchPlaceholder: (label: string) => `Search ${label.toLowerCase()}`,
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToHome: "Back to Home",
  },
  newArrivals: {
    loading: "Loading new arrivals…",
    title: "New Arrivals",
    subtitle:
      "Fresh arrivals from across the live boutique collection, ready to browse by product or by category.",
    emptyTitle: "New arrivals will appear here soon.",
    emptyCopy: "As new products are activated in the catalog, this page will automatically populate.",
    browseCategory: (label: string) => `Browse ${label}`,
  },
  productCard: {
    emptyImage: "Coming Soon",
    fallbackDescription: "Boutique ethnic style",
    inclusiveOfGst: "Inclusive of GST",
    reviewsLabel: (rating: number, count: number) => `${rating.toFixed(1)} ★ (${count})`,
    viewDetails: "Shop Now",
    saveToWishlist: "Save to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
  },
  product: {
    loading: "Loading product…",
    notFound: "Product not found.",
    variantFallback: "Variant",
    descriptionFallback: "Description coming soon.",
    dryCleanFallback: "Dry clean guidance will be added shortly.",
    shippingFallback: "Shipping details coming soon.",
    returnsFallback: "Return and exchange details coming soon.",
    returnableYes: "Yes",
    returnableNo: "No",
    inStock: "In stock",
    futureLaunchVisible: "Made visible for future launch",
    inclusiveOfGst: "Inclusive of GST",
    selectVariant: "Select Variant",
    selectSize: "Select Size",
    stockKeyLabel: "Stock Key",
    fallbackSize: "Size",
    addToCart: "Add to Cart",
    saveToWishlist: "Save to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    wishlistSaved: "Saved to wishlist",
    wishlistRemoved: "Removed from wishlist",
    wishlistFailed: "Unable to update wishlist",
    tabs: {
      description: "Description",
      dryClean: "Dry Clean",
      shipping: "Shipping",
      returns: "Return & Exchange",
    },
    recentlyViewed: "Recently Viewed",
    sameCategoryInspiration: "Same Category Inspiration",
    recentlyViewedEmpty:
      "Start browsing this category to build your recently viewed rail.",
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToCategory: (slug: string) => `Back to ${slug}`,
    reviewsTitle: "Customer Reviews",
    reviewsSubtitle: "Ratings from customers who have tried this product.",
    reviewsEmpty: "No approved reviews yet.",
    reviewsLoading: "Loading reviews...",
    reviewSummaryEmpty: "No ratings yet",
    verifiedBuyer: "Verified Buyer",
    signInToReview: "Sign in to write a review",
    writeReviewTitle: "Write a review",
    reviewAlreadySubmitted: "You already submitted a review for this product.",
    reviewPendingModeration: "Your review is waiting for moderation.",
    reviewRejected: "Your review is currently rejected by moderation.",
    reviewHidden: "Your review is hidden from public view.",
    reviewSubmitted: "Your review was submitted and is awaiting approval.",
    reviewPublished: "Your review was published.",
    reviewFields: {
      rating: "Rating",
      title: "Review title",
      comment: "Review comment",
    },
    reviewSubmit: "Submit Review",
    reviewSubmitting: "Submitting...",
    guestReviewPrompt: "Guests can read reviews but must sign in to post one.",
  },
  checkout: {
    title: "Checkout",
    subtitle: "Review your bag, keep only the lines you want, and continue to delivery confirmation.",
    emptyTitle: "Your cart is empty.",
    emptyCopy: "Add products to your cart before starting checkout.",
    continueToConfirmation: "Continue to Confirmation",
    moveToWishlist: "Move to Wishlist",
    movedToWishlist: "Moved to wishlist",
    moveToWishlistFailed: "Unable to move this item to wishlist",
    confirmationTitle: "Confirm Delivery",
    confirmationSubtitle: "Select the delivery address for this order before you pay.",
    payButton: (amount: string) => `Pay ${amount}`,
    placeOrderFailed: "Unable to place this order right now",
    couponLabel: "Exchange Coupon",
    couponPlaceholder: "Enter coupon code",
    couponApply: "Apply Coupon",
    couponRemove: "Remove Coupon",
    couponApplied: "Coupon applied",
    couponRemoved: "Coupon removed",
    couponForfeitureWarning: "Unused coupon balance will be forfeited after order confirmation.",
    confirmOrderButton: "Confirm Order",
    stockChanged: "One or more cart items changed before checkout could complete",
    stockChangedRecovery: "One or more items changed while you were checking out. Review your cart and update unavailable lines before placing the order again.",
    noAddressTitle: "Add a delivery address to continue.",
    noAddressCopy: "Save a delivery address below, then confirm the order.",
    addressSection: "Delivery Address",
    addAddress: "Add New Address",
    selectAddress: "Select Address",
    addressSaved: "Address saved",
    summaryTitle: "Order Summary",
    subtotalLabel: "Product subtotal",
    gstIncludedLabel: "GST included",
    shippingLabel: "Shipping",
    totalPayableLabel: "Total payable",
    priceInclusiveLabel: "Price inclusive of GST",
    successTitle: "Order Confirmed",
    successSubtitle: "Your order has been placed and payment is treated as completed for this phase.",
    failureTitle: "Payment Failed",
    failureSubtitle: "Payment did not complete. No order was created, and you can retry checkout.",
    successOrder: "Order",
    successAmount: "Amount Paid",
    successAddress: "Delivery Address",
    successItems: "Items",
    viewOrders: "View Orders",
    keepShopping: "Keep Shopping",
  },
  account: {
    auth: {
      kicker: "Customer Account",
      loginTitle: "Login to పూజిత",
      signupTitle: "Create your పూజిత account",
      subtitle:
        "Save addresses, manage wishlist items, and track customer orders from one account.",
      tabs: {
        login: "Login",
        signup: "Signup",
      },
      fields: {
        name: "Name",
        phone: "Phone",
        email: "Email",
        password: "Password",
      },
      submit: {
        busy: "Please wait...",
        login: "Login",
        signup: "Create Account",
      },
      fallbackError: "Unable to continue",
    },
    shell: {
      title: "Account",
    },
    orders: {
      title: "Orders",
      subtitle: "Track fulfilment, shipping, and cancellation progress for each order item.",
      emptyTitle: "No orders yet.",
      emptyCopy:
        "Your confirmed customer orders will appear here as soon as you complete checkout.",
      fallbackError: "Unable to load orders",
      status: "Status",
      paymentStatus: "Payment",
      fulfillmentStatus: "Fulfillment",
      qty: "Qty",
      orderPrefix: "Order #",
      cancel: "Cancel Item",
      cancelBusy: "Cancelling...",
      cancelSuccess: "Item cancelled successfully.",
      cancelRequestedSuccess: "Cancellation requested. The item is now waiting for the cancellation manager.",
      cancelFailed: "Unable to cancel this item",
      cancelBlockedShipped: "Shipped items can no longer be cancelled.",
      cancellationRequested: "Cancellation Requested",
      cancellationRequestedNote: "Your cancellation request has been received and is waiting for handover to the cancellation manager.",
      cancellationReceiptPending: "Awaiting cancellation receipt",
      cancellationReceiptPendingNote: "The item is waiting for the cancellation manager to confirm receipt.",
      inventoryAcceptancePending: "Awaiting cancellation resolution",
      inventoryAcceptanceCancelNote: "The cancellation manager is resolving this item as restocked, damaged, or lost.",
      inventoryAcceptanceReturnNote: "This issue is under internal review.",
      return: "Report an Issue",
      exchange: "Request Exchange",
      returnBusy: "Submitting issue request...",
      exchangeBusy: "Requesting exchange...",
      returnSuccess: "Issue request submitted successfully.",
      exchangeSuccess: "Exchange requested successfully.",
      returnFailed: "Unable to submit an issue request for this item.",
      exchangeFailed: "Unable to request an exchange for this item.",
      returnBlockedPendingDelivery: "Issue or exchange support is available after delivery if eligible.",
      returnBlockedExpired: "The issue or exchange request window has expired.",
      returnBlockedNonReturnable: "This item is not eligible for issue or exchange support.",
      returnBlockedCaseExists: "An issue or exchange case already exists for this item.",
      returnReasonLabel: "Issue details",
      exchangeReasonLabel: "Exchange reason",
      phoneNumberLabel: "Phone Number",
      whatsappNumberLabel: "WhatsApp Number",
      contactHint: "Provide at least one contact number.",
      submitReturn: "Submit Issue Request",
      submitExchange: "Submit Exchange Request",
      activeCaseLabel: "Issue / Exchange Case",
      outboundTracking: "Shipment Tracking",
      collectionTracking: "Collection Tracking",
      returnTracking: "Case Tracking",
      returnReceivedAt: "Case Received At",
      courier: "Courier",
      lifecycle: "Lifecycle",
      deliveredAt: "Delivered At",
      supportNote: "Track fulfillment, cancellations, and issue or exchange cases for each delivered item.",
      returnExchangeStates: {
        RETURN_REQUESTED: "Issue Reported",
        RETURN_UNDER_INVESTIGATION: "Issue Under Investigation",
        RETURN_ACCEPTED: "Issue Accepted",
        RETURN_REJECTED: "Issue Rejected",
        RETURN_IN_TRANSIT: "Item In Review Transit",
        RETURN_RECEIVED: "Item Received For Review",
        RETURN_REFUND_PLACEHOLDER_PENDING: "Manual Resolution Pending",
        EXCHANGE_REQUESTED: "Exchange Requested",
        EXCHANGE_UNDER_INVESTIGATION: "Exchange Under Investigation",
        EXCHANGE_ACCEPTED: "Exchange Accepted",
        EXCHANGE_REJECTED: "Exchange Rejected",
        EXCHANGE_IN_TRANSIT: "Exchange In Transit",
        EXCHANGE_RECEIVED: "Exchange Received",
        EXCHANGE_COUPON_GENERATED: "Exchange Coupon Generated",
      },
      paymentStates: {
        pending: "Pending",
        paid: "Paid",
        payment_failed: "Payment Failed",
        manual_external_resolution: "Manual External Resolution",
      },
      states: {
        PLACED: "Placed",
        PARTIALLY_PICKED: "Partially Picked",
        PICKED: "Picked",
        PARTIALLY_PACKED: "Partially Packed",
        PACKED: "Packed",
        PARTIALLY_SHIPPED: "Partially Shipped",
        SHIPPED: "Shipped",
        PARTIALLY_CANCELLED: "Partially Cancelled",
        CANCELLED: "Cancelled",
        CLOSED: "Closed",
        RESERVED: "Reserved",
        PICKED_FROM_WAREHOUSE: "Picked From Warehouse",
        HANDED_TO_PACKAGING: "Handed To Packaging",
        PACKAGING_RECEIVED: "Packaging Received",
        PACKAGING_IN_PROGRESS: "Packaging In Progress",
        HANDED_TO_SHIPPING: "Handed To Shipping",
        SHIPPING_RECEIVED: "Shipping Received",
        SHIPPING_IN_PROGRESS: "Shipping In Progress",
        DELIVERED: "Delivered",
        CANCELLED_BEFORE_PICKING: "Cancelled Before Picking",
        CANCEL_REQUESTED: "Cancellation Requested",
        HANDED_TO_CANCELLATION: "Handed To Cancellation",
        CANCELLATION_RECEIVED: "Cancellation Received",
        CANCEL_RESTOCKED: "Cancelled And Restocked",
        CANCEL_DAMAGED: "Cancelled As Damaged",
        CANCEL_LOST: "Cancelled As Lost",
        CANCEL_CLOSED: "Cancellation Closed",
      },
    },
    coupons: {
      title: "Coupons",
      subtitle: "Active and used exchange coupons linked to your account.",
      emptyTitle: "No coupons yet.",
      emptyCopy: "Exchange coupons will appear here after an eligible exchange item is received and processed.",
      fallbackError: "Unable to load coupons",
      status: "Status",
      value: "Value",
      validity: "Validity",
      usedAt: "Used At",
    },
    wishlist: {
      title: "Wishlist",
      subtitle: "Saved products stay ready here while you browse the catalog.",
      emptyTitle: "Your wishlist is empty.",
      emptyCopy: "Use the heart icon on product cards or product detail pages to keep products here.",
      remove: "Remove",
      moveToCart: "Move to Cart",
      selectOptions: "Select options",
      movedToCart: "Moved to cart",
      moveToCartFailed: "Unable to move item to cart",
      moveCleanupFailed: "Added to cart, but wishlist removal did not complete",
      fallbackError: "Unable to load wishlist",
    },
    addresses: {
      title: "Saved Addresses",
      subtitle: "Save delivery addresses for a faster checkout and order confirmation.",
      fallbackError: "Unable to load addresses",
      saveFailed: "Unable to save address",
      emptyTitle: "No saved addresses yet.",
      emptyCopy: "Add your first address to make future checkout faster.",
      defaultBadge: "Default",
      defaultCheckbox: "Set as default address",
      actions: {
        save: "Save Address",
        update: "Update Address",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
      },
      fields: {
        fullName: "Full Name",
        phone: "Phone",
        line1: "Address Line 1",
        line2: "Address Line 2",
        city: "City",
        state: "State",
        postalCode: "Postal Code",
        country: "Country",
      },
    },
  },
} as const;
