export const STOREFRONT_STRINGS = {
  brand: {
    name: "Siri Collections",
    fallbackCategoryLabel: "Collection",
    fallbackCategorySlug: "collection",
  },
  navigation: {
    account: {
      welcome: "Welcome",
      welcomeBack: "Hello",
      guestSubtitle: "To access account and manage orders",
      loginSignup: "Login / Signup",
      logout: "Logout",
      orders: "Orders",
      wishlist: "Wishlist",
      savedAddresses: "Saved Addresses",
      customerAccount: "Account",
    },
    cart: {
      unavailable: "Cart is temporarily unavailable",
    },
  },
  home: {
    loading: "Loading storefront…",
    heroEyebrow: "Category First Luxury Storefront",
    heroTitle: "Celebrate every drape with a commerce experience built like Siri Collections.",
    heroCopy:
      "Browse blouse stories first, discover upcoming categories as they launch, and move from cart to confirmed order with the live customer checkout flow.",
    browseCategories: "Browse Categories",
    exploreCategories: "Explore Categories",
    browseByCategory: "Browse by Category",
    allCollectionsStayVisible: "All Collections Stay Visible",
    categoryTreeCopy:
      "Categories come from the active category tree. Launched collections open their live merchandise listings immediately, while unpublished launches can remain visible as coming-soon destinations.",
    liveInventory: "Live Inventory",
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    viewAll: "View All",
    selectedCollection: "Selected Collection",
    liveRailUnavailable:
      "The live blouse rail is temporarily unavailable while the storefront backend recovers.",
    liveRailComingSoonTitle: "The live blouse rail will appear here when merchandise is available.",
    liveRailComingSoonCopy:
      "If the primary live category has no products available yet, the storefront stays intact and waits for the catalog to go live.",
    liveCategoryCopy: (label: string) =>
      `Browse the live ${label.toLowerCase()} catalog with full listing and product detail support.`,
    upcomingCategoryCopy:
      "This category remains visible in the menu and opens a branded coming-soon page until merchandise is launched.",
  },
  category: {
    loading: "Loading category…",
    collection: "Collection",
    filters: "Filters",
    price: "Price",
    loadingMore: "Loading more products...",
    noFilters: "No filters are configured for this live category yet.",
    notFound: "Not Found",
    notFoundTitle: "This category does not exist.",
    notFoundCopy:
      "Choose another collection from the storefront menu. Category pages are generated from the active category tree.",
    comingSoon: "Coming Soon",
    comingSoonTitle: (heading: string) => `${heading} is visible in categories and preparing to launch.`,
    comingSoonCopy:
      "The category page is intentionally published before merchandise arrives. Live categories fetch products automatically once they are launched.",
    listingUnavailable:
      "The live category listing is temporarily unavailable. Category routing is still working, but the catalog data could not be loaded.",
    emptyListingTitle: (heading: string) => `${heading} will appear here soon.`,
    emptyListingCopy:
      "This route is live. Once products are active in the catalog, this listing automatically switches from placeholder state to a full merchandise grid.",
    searchPlaceholder: (label: string) => `Search ${label.toLowerCase()}`,
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToHome: "Back to Home",
  },
  productCard: {
    emptyImage: "Coming Soon",
    fallbackDescription: "Curated collection",
    viewDetails: "View Details",
    saveToWishlist: "Save to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
  },
  product: {
    loading: "Loading product…",
    notFound: "Product not found.",
    variantFallback: "Variant",
    descriptionFallback: "Description coming soon.",
    dryCleanFallback: "Dry clean guidance will be added shortly.",
    shippingFallback: "Shipping details coming soon.",
    returnsFallback: "Return and exchange details coming soon.",
    returnableYes: "Yes",
    returnableNo: "No",
    inStock: "In stock",
    futureLaunchVisible: "Made visible for future launch",
    selectVariant: "Select Variant",
    selectSize: "Select Size",
    stockKeyLabel: "Stock Key",
    fallbackSize: "Size",
    addToCart: "Add to Cart",
    saveToWishlist: "Save to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    wishlistSaved: "Saved to wishlist",
    wishlistRemoved: "Removed from wishlist",
    wishlistFailed: "Unable to update wishlist",
    tabs: {
      description: "Description",
      dryClean: "Dry Clean",
      shipping: "Shipping",
      returns: "Return & Exchange",
    },
    recentlyViewed: "Recently Viewed",
    sameCategoryInspiration: "Same Category Inspiration",
    recentlyViewedEmpty:
      "Start browsing this category to build your recently viewed rail.",
    featuredPicks: "Featured Picks",
    youMayAlsoLike: "You May Also Like",
    backToCategory: (slug: string) => `Back to ${slug}`,
  },
  checkout: {
    title: "Checkout",
    subtitle: "Review your bag, keep only the lines you want, and continue to delivery confirmation.",
    emptyTitle: "Your cart is empty.",
    emptyCopy: "Add products to your cart before starting checkout.",
    continueToConfirmation: "Continue to Confirmation",
    moveToWishlist: "Move to Wishlist",
    movedToWishlist: "Moved to wishlist",
    moveToWishlistFailed: "Unable to move this item to wishlist",
    confirmationTitle: "Confirm Delivery",
    confirmationSubtitle: "Select the delivery address for this order before you pay.",
    payButton: (amount: string) => `Pay ${amount}`,
    paymentFailedButton: "Payment Failed",
    placeOrderFailed: "Unable to place this order right now",
    stockChanged: "One or more cart items changed before checkout could complete",
    noAddressTitle: "Add a delivery address to continue.",
    noAddressCopy: "Save a delivery address below, then confirm the order.",
    addressSection: "Delivery Address",
    addAddress: "Add New Address",
    selectAddress: "Select Address",
    addressSaved: "Address saved",
    summaryTitle: "Order Summary",
    successTitle: "Order Confirmed",
    successSubtitle: "Your order has been placed and payment is treated as completed for this phase.",
    failureTitle: "Payment Failed",
    failureSubtitle: "This simulated payment failure created an order record for admin visibility, but it did not enter fulfillment.",
    successOrder: "Order",
    successAmount: "Amount Paid",
    successAddress: "Delivery Address",
    successItems: "Items",
    viewOrders: "View Orders",
    keepShopping: "Keep Shopping",
  },
  account: {
    auth: {
      kicker: "Customer Account",
      loginTitle: "Login to Siri",
      signupTitle: "Create your Siri account",
      subtitle:
        "Save addresses, manage wishlist items, and track customer orders from one account.",
      tabs: {
        login: "Login",
        signup: "Signup",
      },
      fields: {
        name: "Name",
        phone: "Phone",
        email: "Email",
        password: "Password",
      },
      submit: {
        busy: "Please wait...",
        login: "Login",
        signup: "Create Account",
      },
      fallbackError: "Unable to continue",
    },
    shell: {
      title: "Account",
    },
    orders: {
      title: "Orders",
      subtitle: "Track shipment, cancellation, return, and refund progress for each order item.",
      emptyTitle: "No orders yet.",
      emptyCopy:
        "Your confirmed customer orders will appear here as soon as you complete checkout.",
      fallbackError: "Unable to load orders",
      status: "Status",
      paymentStatus: "Payment",
      fulfillmentStatus: "Fulfillment",
      qty: "Qty",
      orderPrefix: "Order #",
      cancel: "Cancel Item",
      cancelBusy: "Cancelling...",
      cancelSuccess: "Item cancelled and stock restored",
      cancelRequestedSuccess: "Cancellation requested. The packed item will be unpacked and cancelled by the admin team.",
      cancelFailed: "Unable to cancel this item",
      cancelBlockedPacked: "Packed items can only be cancelled after the admin team unpacks them.",
      cancelBlockedShipped: "Shipped items can no longer be cancelled.",
      cancellationRequested: "Cancellation Requested",
      cancellationRequestedNote: "Your cancellation request has been received. The admin team will unpack this item before cancelling it.",
      return: "Request Return",
      returnBusy: "Requesting return...",
      returnSuccess: "Return request submitted",
      returnFailed: "Unable to request return for this item",
      returnBlockedPendingDelivery: "This item becomes returnable only after it is delivered.",
      returnBlockedExpired: "The return window for this item has expired.",
      returnBlockedNonReturnable: "This item is not returnable.",
      outboundTracking: "Shipment Tracking",
      collectionTracking: "Collection Tracking",
      lifecycle: "Lifecycle",
      deliveredAt: "Delivered At",
      supportNote: "Exchange is handled as return, refund, and a fresh order in this version.",
      paymentStates: {
        pending: "Pending",
        paid: "Paid",
        payment_failed: "Payment Failed",
        refund_pending: "Refund Pending",
        partially_refunded: "Partially Refunded",
        refunded: "Refunded",
      },
      states: {
        processing: "Processing",
        packed: "Packed",
        unpacked: "Unpacked",
        shipped: "Shipped",
        delivered: "Delivered",
        cancelled: "Cancelled",
        cancelled_by_admin: "Cancelled by Admin",
        return_requested: "Return Requested",
        collection_scheduled: "Collection Scheduled",
        return_in_transit: "Return In Transit",
        return_received: "Return Received",
        refund_completed: "Refund Completed",
      },
    },
    wishlist: {
      title: "Wishlist",
      subtitle: "Saved products stay ready here while you browse the catalog.",
      emptyTitle: "Your wishlist is empty.",
      emptyCopy: "Use the heart icon on product cards or product detail pages to keep products here.",
      remove: "Remove",
      moveToCart: "Move to Cart",
      selectOptions: "Select options",
      movedToCart: "Moved to cart",
      moveToCartFailed: "Unable to move item to cart",
      moveCleanupFailed: "Added to cart, but wishlist removal did not complete",
      fallbackError: "Unable to load wishlist",
    },
    addresses: {
      title: "Saved Addresses",
      subtitle: "Save delivery addresses for a faster checkout and order confirmation.",
      fallbackError: "Unable to load addresses",
      saveFailed: "Unable to save address",
      emptyTitle: "No saved addresses yet.",
      emptyCopy: "Add your first address to make future checkout faster.",
      defaultBadge: "Default",
      defaultCheckbox: "Set as default address",
      actions: {
        save: "Save Address",
        update: "Update Address",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
      },
      fields: {
        fullName: "Full Name",
        phone: "Phone",
        line1: "Address Line 1",
        line2: "Address Line 2",
        city: "City",
        state: "State",
        postalCode: "Postal Code",
        country: "Country",
      },
    },
  },
} as const;
