export const ADMIN_UI_STRINGS = {
  brand: {
    portalTitle: "Admin Portal",
  },
  shell: {
    notSignedIn: "Not signed in",
    authStatusPrefix: "Auth status:",
    authBootstrapTitle: "Auth bootstrap diagnostic",
    profile: "Profile",
    logout: "Logout",
  },
  login: {
    title: "Admin Login",
    fields: {
      email: "Email",
      password: "Password",
    },
    signIn: "Sign In",
    signingIn: "Signing in...",
    failed: "Login failed",
    localUrlsTitle: "Local URLs",
    localUrlsCopy:
      "The admin menu is permission-based, so it becomes available after a successful sign-in.",
  },
  menu: {
    profile: "Profile",
    sessions: "Sessions",
    users: "Users",
    roles: "Roles",
    permissions: "Permissions",
    categories: "Categories",
    products: "Products",
    ordersDashboard: "Orders Dashboard",
    ordersMetrics: "Orders Metrics",
    orders: "Orders Queue",
    inventory: "Inventory",
    systemHealth: "System Health",
    audit: "Audit",
  },
  common: {
    refresh: "Refresh",
    create: "Create",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    previous: "Previous",
    next: "Next",
    action: "Action",
    status: "Status",
    loadingProducts: "Loading products...",
    loadingOrders: "Loading orders...",
    loadingInventory: "Loading inventory...",
    noImage: "no image",
    yes: "Yes",
    no: "No",
  },
  localUrls: {
    adminPortal: "Admin portal",
    gatewayApi: "Gateway API",
    gatewayHealth: "Gateway health",
    storefront: "Customer storefront",
  },
  health: {
    title: "System Health",
    up: "UP",
    down: "DOWN",
    services: {
      gateway: "Gateway",
      auth: "Auth",
      catalog: "Catalog",
      product: "Product",
    },
  },
  categories: {
    title: "Categories",
    createCategory: "Create Category",
    table: {
      name: "Name",
      slug: "Slug",
      sort: "Sort",
      status: "Status",
      action: "Action",
    },
    tree: {
      collapse: "Collapse",
      expand: "Expand",
    },
  },
  orders: {
    title: "Orders",
    dashboardTitle: "Order Operations Dashboard",
    openQueue: "Open Orders Queue",
    currentWorkload: "Current Workload",
    summaryReceived: "Received",
    summaryPacked: "Packed",
    summaryShipped: "Shipped",
    summaryDelivered: "Delivered",
    summaryCancelled: "Cancelled",
    summaryCancelledByAdmin: "Cancelled By Admin",
    summaryPaymentFailed: "Payment Failed",
    summaryTotal: "Total Orders",
    metricsTitle: "Order Metrics",
    metricsSubtitle: "Sales, revenue, and cancellation signals across all orders.",
    backToDashboard: "Back to Dashboard",
    backToQueue: "Back to Queue",
    paymentStateLabel: "Payment",
    allPayments: "All payments",
    searchLabel: "Search",
    stockKeyLabel: "Stock Key",
    stateLabel: "State",
    allStates: "All states",
    headers: ["Order", "Placed", "Items", "State", "Amount"] as const,
    detailTitle: "Order Details",
    itemStateLabel: "Item state",
    outboundTrackingLabel: "Outbound Tracking",
    collectionTrackingLabel: "Collection Tracking",
    nextActionsLabel: "Next Actions",
    cancelItem: "Cancel + Restock",
    unpackCancelItem: "Unpack and Cancel",
    packItem: "Mark Packed",
    shipItem: "Ship Item",
    requestCollection: "Schedule Collection",
    markReturnInTransit: "Mark Return In Transit",
    markReturnReceived: "Mark Return Received",
    markRefundCompleted: "Mark Refund Completed",
    cancellationRequested: "Cancellation Requested",
    cancellationRequestedHint: "Customer asked to cancel this packed item. Unpack and cancel it before any restock happens.",
    unpackConfirm: "Confirm unpack and restock this packed item before cancelling it?",
    cancelConfirm: "Cancel this processing item and restock it immediately?",
    outboundTrackingRequired: "Enter an outbound tracking number before shipping.",
    collectionTrackingRequired: "Enter a collection tracking number before scheduling pickup.",
    orderStatusPrefix: "Order Status",
    paymentStatusPrefix: "Payment Status",
    paymentStates: {
      pending: "Pending",
      paid: "Paid",
      payment_failed: "Payment Failed",
      refund_pending: "Refund Pending",
      partially_refunded: "Partially Refunded",
      refunded: "Refunded",
    },
    failedPaymentBlocked: "Failed-payment orders are visible for review only. They cannot enter fulfillment.",
    metricsPaidOrders: "Paid Orders",
    metricsFailedPayments: "Failed Payments",
    metricsGrossRevenue: "Gross Revenue",
    metricsRefundTotal: "Refund Total",
    metricsSoldItems: "Sold Items",
    metricsCancelledItems: "Cancelled Items",
    metricsSoldByDay: "Sold By Day",
    metricsSoldByMonth: "Sold By Month",
    metricsSoldByQuarter: "Sold By Quarter",
    metricsCancelledByDay: "Cancelled By Day",
    metricsCancelledByMonth: "Cancelled By Month",
    metricsCancelledByQuarter: "Cancelled By Quarter",
    metricsTopSellingProducts: "Top Selling Products",
    metricsTopSellingCategories: "Top Selling Categories",
    metricsTopCancelledProducts: "Top Cancelled Products",
    metricsTopCancelledCategories: "Top Cancelled Categories",
    metricsNoData: "No metrics available yet.",
    states: {
      processing: "Processing",
      packed: "Packed",
      unpacked: "Unpacked",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
      cancelled_by_admin: "Cancelled by Admin",
      return_requested: "Return Requested",
      collection_scheduled: "Collection Scheduled",
      return_in_transit: "Return In Transit",
      return_received: "Return Received",
      refund_completed: "Refund Completed",
    },
  },
  inventory: {
    title: "Stock",
    summaryTitle: "Inventory Summary",
    searchLabel: "Search",
    searchPlaceholder: "Search by SKU, size, title, or slug",
    productLabel: "Product",
    remainingQuantity: "Remaining",
    stockKeyLabel: "Stock Key",
    sizeLabel: "Size",
    skuCount: "SKUs",
    productsCount: "Products",
    stockDetailsTitle: "Stock Breakdown",
    orderDetailsTitle: "Order Details",
    expandRow: "Expand",
    collapseRow: "Collapse",
    initialQuantity: "Initial",
    currentQuantity: "Current",
    soldQuantity: "Sold",
    reorderLevel: "Reorder Level",
    soldInOrders: "Sold in Orders",
    noSales: "No sales yet",
    filteredSkus: "Filtered SKUs",
    currentUnits: "Current Units",
    soldUnits: "Sold Units",
    lowStock: "Low Stock",
    lowStockBadge: "Needs attention",
    lowStockHint: "Current stock is at or below the reorder level.",
    skuSuffix: "SKU",
    editorTitle: "Update Inventory",
    quantityLabel: "Current quantity",
    reorderLevelLabel: "Reorder level",
    quantityHelp: "Adjust the live sellable quantity for this SKU.",
    reorderLevelHelp: "Flag this SKU when current stock reaches this threshold.",
    saveError: "Enter non-negative numbers for quantity and reorder level.",
    emptyState: "No inventory matches the current filters.",
    noOrderDetails: "No order details for this product.",
  },
  products: {
    title: "Products",
    categoryLabel: "Category",
    allCategories: "All categories",
    createProduct: "Create Product",
    defaultVariantMissing: "-",
    variants: "Variants",
    publish: "Publish",
    unpublish: "Unpublish",
    headers: [
      "Variant",
      "Title",
      "Slug",
      "Default Variant",
      "Colors",
      "Care",
      "Discount",
      "Featured",
      "Status",
      "Actions",
    ] as const,
    deleteConfirm: (title: string) =>
      `Delete product "${title}"? This will permanently delete product, variants and stock.`,
  },
} as const;
