export const ADMIN_UI_STRINGS = {
  brand: {
    portalTitle: "Admin Portal",
  },
  shell: {
    notSignedIn: "Not signed in",
    authStatusPrefix: "Auth status:",
    authBootstrapTitle: "Auth bootstrap diagnostic",
    profile: "Profile",
    logout: "Logout",
  },
  login: {
    title: "Admin Login",
    fields: {
      email: "Email",
      password: "Password",
    },
    signIn: "Sign In",
    signingIn: "Signing in...",
    failed: "Login failed",
    localUrlsTitle: "Local URLs",
    localUrlsCopy:
      "The admin menu is permission-based, so it becomes available after a successful sign-in.",
  },
  menu: {
    profile: "Profile",
    sessions: "Sessions",
    users: "Users",
    roles: "Roles",
    permissions: "Permissions",
    categories: "Categories",
    products: "Products",
    ordersDashboard: "Overview Dashboard",
    ordersMetrics: "Sales Dashboard",
    processingManager: "Processing Manager",
    packagingManager: "Packaging Manager",
    shippingOperator: "Shipping Operator",
    cancellationManager: "Cancellation Manager",
    returnExchangeManager: "Return & Exchange",
    orders: "Orders Overview",
    inventory: "Inventory",
    productReviews: "Reviews",
    systemHealth: "System Health",
    audit: "Audit",
  },
  common: {
    refresh: "Refresh",
    create: "Create",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    previous: "Previous",
    next: "Next",
    action: "Action",
    status: "Status",
    loadingProducts: "Loading products...",
    loadingOrders: "Loading orders...",
    loadingInventory: "Loading inventory...",
    noImage: "no image",
    yes: "Yes",
    no: "No",
  },
  localUrls: {
    adminPortal: "Admin portal",
    gatewayApi: "Gateway API",
    gatewayHealth: "Gateway health",
    storefront: "Customer storefront",
  },
  health: {
    title: "System Health",
    up: "UP",
    down: "DOWN",
    services: {
      gateway: "Gateway",
      auth: "Auth",
      catalog: "Catalog",
      product: "Product",
    },
  },
  categories: {
    title: "Categories",
    createCategory: "Create Category",
    table: {
      name: "Name",
      slug: "Slug",
      sort: "Sort",
      status: "Status",
      action: "Action",
    },
    tree: {
      collapse: "Collapse",
      expand: "Expand",
    },
  },
  orders: {
    title: "Orders",
    overviewEyebrow: "Owner / Manager Overview",
    overviewTitle: "Business performance at a glance",
    overviewSubtitle:
      "Track demand, fulfillment pressure, and inventory risk from one role-aware workspace built on live order and stock data.",
    overviewDateRange: "Date range",
    dashboardTabsLabel: "Order dashboard tabs",
    dashboardTabOverview: "Overview",
    dashboardTabFulfillment: "Fulfillment",
    dashboardTabEscalations: "Escalations",
    overviewLoading: "Loading dashboard insights...",
    overviewEmpty: "No dashboard data is available for the selected role and date range yet.",
    overviewRestricted: "Restricted",
    overviewRevenue: "Total Payable Revenue",
    overviewOrders: "Orders",
    overviewAverageOrderValue: "Average Payable Order Value",
    overviewPendingOrders: "Pending Orders",
    overviewPendingProcessing: "Pending Processing Orders",
    overviewPendingPackaging: "Pending Packaging Orders",
    overviewPendingShipping: "Pending Shipping Orders",
    overviewIssueExchangeInvestigations: "Issue / Exchange Investigations",
    overviewCashCouponsGenerated: "Cash Coupons Generated",
    overviewCashCouponsConsumed: "Cash Coupons Consumed",
    overviewFailedCheckouts: "Failed Checkouts",
    overviewAbandonedCheckouts: "Abandoned Checkouts",
    overviewLowStock: "Low Stock Variants",
    overviewOutOfStock: "Out Of Stock Variants",
    overviewCancelledOrders: "Cancelled Orders",
    overviewTrendTitle: "Sales Trend",
    overviewTrendEmpty: "No sales activity in this time window yet.",
    overviewStatusEyebrow: "Fulfillment Snapshot",
    overviewStatusTitle: "Orders By Status",
    overviewStatusEmpty: "No orders in the selected range.",
    overviewActionEyebrow: "Immediate Attention",
    overviewActionTitle: "Action Required",
    overviewActionClear: "Nothing urgent is waiting right now.",
    overviewActionHint: "Open queue",
    overviewLowStockAction: "Low stock SKUs",
    overviewOutOfStockAction: "Out of stock SKUs",
    overviewRecentEyebrow: "Latest Activity",
    overviewRecentTitle: "Recent Orders",
    overviewRecentEmpty: "No recent orders in the selected range.",
    overviewTopSellingEyebrow: "Commercial Leaders",
    overviewTopSellingTitle: "Top Selling Products",
    overviewTopSellingEmpty: "Top sellers will appear after completed sales are recorded.",
    overviewInventoryEyebrow: "Stock Risk",
    overviewLowStockTitle: "Low Stock Alerts",
    overviewLowStockEmpty: "No low-stock SKUs need attention right now.",
    overviewOutOfStockTitle: "Out Of Stock",
    overviewOutOfStockEmpty: "No products are currently out of stock.",
    overviewLowStockHelp: "Low Stock Variants: variants with available stock less than 2 and greater than 0.",
    overviewOutOfStockHelp: "Out of Stock Variants: variants with available stock equal to 0.",
    overviewPartialShipmentHelp: "Partially Shipped means at least one item in the order is shipped or delivered while other items in the same order are still pending fulfillment.",
    rangeToday: "Today",
    rangeThisWeek: "This week",
    rangeLast7Days: "Last 7 days",
    rangeThisMonth: "This month",
    rangeLast30Days: "Last 30 days",
    rangeThisYear: "This year",
    rangeCustom: "Custom",
    customFrom: "From",
    customTo: "To",
    overviewStatusClickHint: "Open filtered orders",
    fulfillmentTitle: "Fulfillment Visibility",
    fulfillmentSubtitle: "Track every non-escalated processing, packaging, shipping, and shipped item in one place.",
    fulfillmentLoading: "Loading fulfillment items...",
    fulfillmentEmpty: "No non-escalated fulfillment items match the current filters.",
    fulfillmentFilterLabel: "Fulfillment filter",
    escalationTitle: "SLA Escalations",
    escalationSubtitle: "Review only SLA-violated items that currently require oversight.",
    escalationLoading: "Loading escalations...",
    escalationEmpty: "No SLA-violated items need oversight right now.",
    customerOrderedDateLabel: "Customer Ordered Date",
    targetCompletionDateLabel: "Target Completion Date",
    laneAssignedAtLabel: "Lane Assigned Date",
    lastActionedAtLabel: "Last Actioned At",
    currentStageLabel: "Current Stage",
    currentOwnerLabel: "Current Owner",
    hoursInLaneLabel: "Hours In Lane",
    slaStatusLabel: "SLA Status",
    violationReasonLabel: "Violation Reason",
    delayedIndicator: "Delayed",
    violatedIndicator: "Escalated",
    staleTaskError: "This task changed after you loaded it. Refresh and try again.",
    salesTitle: "Sales Dashboard",
    salesSubtitle: "Revenue, order, and product performance with live period comparisons.",
    salesWeeklyComparison: "Week over week",
    salesMonthlyComparison: "Month over month",
    salesYearlyComparison: "Year over year",
    salesCurrentPeriod: "Current",
    salesPreviousPeriod: "Previous",
    salesChange: "Change",
    salesCurrentYearTrend: "Month by month revenue",
    salesWeeklyRangeTrend: "Weekly revenue for selected range",
    salesTopProducts: "Top selling products",
    salesTopProductsEmpty: "Top selling products will appear after sales are recorded.",
    ordersDashboardTitle: "Orders Dashboard",
    ordersDashboardSubtitle: "Track resolved order status, partial shipments, and filtered order lists.",
    ordersFilterStatus: "Order status",
    ordersFilterSearch: "Search orders",
    ordersFilterClear: "Clear filters",
    ordersListEmpty: "No orders match the current filters.",
    ordersListTitle: "Orders List",
    partiallyShippedOrders: "Partially Shipped",
    dashboardTitle: "Order Operations Dashboard",
    openQueue: "Open Processing Queue",
    currentWorkload: "Current Workload",
    operationsSubtitle: "Admin-only operations overview",
    operationsTabsLabel: "Order operations tabs",
    operationsSearchPlaceholder: "Search by order ID, product, SKU, customer, courier, or tracking",
    operationsCourierPlaceholder: "Filter by courier name",
    summaryReceived: "Processing Manager",
    summaryPacked: "Packaging Manager",
    summaryShippingQueue: "Shipping Operator",
    summaryShippingReceived: "Shipping Received",
    summaryShipped: "Shipped",
    summaryCancellationReceiptPending: "Cancellation Manager",
    summaryReturnExchangeQueue: "Return & Exchange",
    summaryCancelled: "Cancelled",
    summaryTotal: "Total Orders",
    summaryQueueCount: "Queue Orders",
    metricsTitle: "Order Metrics",
    metricsSubtitle: "Sales, revenue, and cancellation signals across all orders.",
    backToDashboard: "Back to Dashboard",
    backToQueue: "Back to Orders Overview",
    orderSummaryStatusLabel: "Order Summary",
    laneSummaryLabel: "Lane Summary",
    paymentStateLabel: "Payment",
    merchandiseTotalLabel: "Product total",
    discountLabel: "Discount",
    gstIncludedLabel: "GST included",
    shippingLabel: "Shipping",
    totalPayableLabel: "Total payable",
    searchLabel: "Search",
    sortLabel: "Sort",
    filterStatusLabel: "Filter by status",
    filterCourierLabel: "Filter by courier",
    allStatuses: "All statuses",
    stockKeyLabel: "Stock Key",
    headers: ["Order", "Placed", "Items", "State", "Amount"] as const,
    detailTitle: "Order Details",
    itemStateLabel: "Item state",
    itemQuantityLabel: "Qty",
    physicalOwnerLabel: "Physical Owner",
    packageVerificationLabel: "Package Verification",
    labelStatusLabel: "Label Status",
    labelReprintsLabel: "Label Reprints",
    courierLabel: "Courier",
    pendingHandoverLabel: "Pending Handover",
    cancellationReasonLabel: "Cancellation Reason",
    shippingAddress: "Shipping Address",
    itemsInQueue: "Items In Queue",
    outboundTrackingLabel: "Outbound Tracking",
    processingTaskBoardTitle: "Today’s Picking Board",
    processingTaskBoardSubtitle: "Work the queue as a task list, then print a warehouse-friendly pick sheet before walking inventory.",
    processingPendingSection: "Pending Picking",
    processingAttentionSection: "Pending / Overdue",
    processingReadySection: "Picked / Ready For Handover",
    processingProcessedSection: "Processed Orders",
    processingCancellationSection: "Cancellation Requested",
    processingTaskSectionEmpty: "No items match this section right now.",
    processingTaskOrderCount: (count: number) => `${count} ${count === 1 ? "item" : "items"}`,
    processingPrintPickList: "Print Pick List",
    processingPrintHandoverList: "Print Handover List",
    processingPrintProcessedList: "Print Processed List",
    processingPrintCancellationList: "Print Cancellation List",
    processingPrintEmpty: "No items are available to print for this bucket.",
    processingSelectionInputLabel: "Select pending pick item",
    processingSelectAllPending: "Select All",
    processingPrintSelectedCount: (count: number) => `${count} selected for printing`,
    processingPrintDefaultHint: (count: number) => `Prints all ${count} items in this bucket when nothing is selected.`,
    processingPickListTitle: "Warehouse Pick List",
    processingHandoverListTitle: "Processing To Packaging Handover List",
    processingProcessedListTitle: "Processing Processed Orders",
    processingCancellationListTitle: "Processing Cancellation List",
    processingPrintGeneratedAt: "Generated At",
    processingPrintOrder: "Order",
    processingPrintStorageReference: "Storage Ref",
    processingPrintNotes: "Reference / Notes",
    processingTaskOpenOrder: "Open order details",
    processingAwaitingReceiptHint: "Already handed to packaging. Waiting for packaging to confirm receipt.",
    processingProcessedHint: "Processing work is complete for this item.",
    processingPrintPreparedBy: "Prepared By",
    processingPrintReceivedBy: "Received By",
    processingPrintSignatureLine: "Signature: ____________________",
    processingPrintDateLine: "Date / Time: ____________________",
    packagingTaskBoardTitle: "Packaging Work Board",
    packagingTaskBoardSubtitle: "Handle packaging receipts, active packing work, and shipping handover lists from one consistent lane workspace.",
    packagingPendingSection: "Received / Pending Packaging",
    packagingReadySection: "Packaged / Ready For Shipping Handover",
    packagingProcessedSection: "Processed Orders",
    packagingCancellationSection: "Cancellation Requested",
    packagingPrintWorkList: "Print Packaging Work List",
    packagingPrintHandoverList: "Print Packaged Handover List",
    packagingPrintProcessedList: "Print Processed List",
    packagingPrintCancellationList: "Print Cancellation List",
    packagingWorkListTitle: "Packaging Work List",
    packagingHandoverListTitle: "Packaging To Shipping Handover List",
    packagingProcessedListTitle: "Packaging Processed Orders",
    packagingCancellationListTitle: "Packaging Cancellation List",
    packagingAwaitingReceiptHint: "Awaiting packaging receipt confirmation from the handover.",
    packagingPendingWorkHint: "Receipt confirmed. Start packaging work.",
    packagingInProgressHint: "Complete verification, label printing, and packing.",
    packagingReadyForShippingHint: "Packaged and ready to hand over to shipping.",
    packagingProcessedHint: "Packaging work is complete for this item.",
    packagingModalTitle: "Packaging Work",
    packagingModalVerifyTitle: "Verify Package",
    packagingModalVerifyHelp: "Internal package check / quality check before the item can be marked packed.",
    packagingModalLabelTitle: "Print Label",
    packagingModalLabelHelp: "Utility prerequisite. The backend requires a printed label before packing can be completed.",
    packagingModalPackedTitle: "Mark Packed",
    packagingModalPackedHelp: "This is the actual workflow transition that moves the item into the shipping handover bucket.",
    packagingModalReadyToPack: "Verification and printed label are complete.",
    packagingModalBlocked: "Complete the package check and print the label before marking this item packed.",
    shippingTaskBoardTitle: "Shipping Work Board",
    shippingTaskBoardSubtitle: "Manage shipping receipts, dispatch work, completed shipments, and cancellations with the same operational pattern.",
    shippingPendingSection: "Received / Pending Shipping",
    shippingCompletedSection: "Shipped / Completed",
    shippingCancellationSection: "Cancellation Requested",
    shippingPrintWorkList: "Print Shipping Work List",
    shippingPrintDispatchList: "Print Shipped / Dispatch List",
    shippingPrintCancellationList: "Print Cancellation List",
    shippingWorkListTitle: "Shipping Work List",
    shippingDispatchListTitle: "Shipping Dispatch List",
    shippingCancellationListTitle: "Shipping Cancellation List",
    shippingAwaitingReceiptHint: "Awaiting shipping receipt confirmation from the handover.",
    shippingPendingWorkHint: "Receipt confirmed. Start shipping work.",
    shippingInProgressHint: "Assign courier, enter tracking, and mark the shipment complete.",
    shippingCompletedHint: "Shipment completed and ready for dispatch record printing.",
    shippingCancellationPendingReceiptHint: "Cancellation requested during handover. Confirm or reject receipt before moving to cancellation handling.",
    shippingModalTitle: "Ship Item",
    shippingModalHelp: "Save courier and tracking together, then move the item directly into the shipped/completed bucket.",
    shippingModalCourierLabel: "Courier / Carrier Name",
    shippingModalCourierHelp: "Enter the courier or carrier responsible for this shipment.",
    shippingModalTrackingLabel: "Tracking Number",
    shippingModalTrackingHelp: "Enter the outbound tracking number that will be shared with the customer.",
    shippingModalValidation: "Enter both courier and tracking number to ship this item.",
    dashboardExecutiveSummaryTitle: "Executive Summary",
    dashboardOperationsTitle: "Operational Drilldown",
    dashboardStockHealthTitle: "Stock Health",
    dashboardCategoryRiskTitle: "Category Risk",
    dashboardRecentUpdatesTitle: "Recent Stock Updates",
    dashboardTopCategoriesTitle: "Top Categories",
    viewProduct: "View Product",
    markDelivered: "Mark Delivered",
    markDeliveredTemporary: "Temporary action until delivery integration is implemented.",
    expandDetails: "Expand Details",
    collapseDetails: "Collapse Details",
    noOrderItemsFound: "No order items found",
    orderIdLabel: "Order ID",
    orderItemIdLabel: "Order Item ID",
    productNameLabel: "Product Name",
    productPriceLabel: "Product Price",
    customerNameLabel: "Customer Name",
    customerContactLabel: "Customer Contact",
    createdAtLabel: "Created Date",
    lastUpdatedLabel: "Last Updated",
    nextActionsLabel: "Next Actions",
    cancelItem: "Cancel Item",
    pickItem: "Pick Item",
    handoverToPackaging: "Handover To Packaging",
    confirmPackagingReceipt: "Confirm Packaging Receipt",
    rejectPackagingReceipt: "Reject Packaging Receipt",
    startPackaging: "Start Packaging",
    packageItem: "Package Item",
    verifyPackage: "Verify Package",
    printLabel: "Print Label",
    viewLabel: "View Label",
    reprintLabel: "Reprint Label",
    markPacked: "Mark Packed",
    handoverToShipping: "Handover To Shipping",
    confirmShippingReceipt: "Confirm Shipping Receipt",
    rejectShippingReceipt: "Reject Shipping Receipt",
    startShipping: "Start Shipping",
    assignCourier: "Assign Courier",
    enterTrackingNumber: "Enter Tracking Number",
    shipItem: "Ship Item",
    handoverToCancellation: "Handover To Cancellation",
    confirmCancellationReceipt: "Confirm Cancellation Receipt",
    restockCancelledItem: "Restock Cancelled Item",
    markCancelledDamaged: "Mark Cancelled Item Damaged",
    markCancelledLost: "Mark Cancelled Item Lost",
    assignCourierPrompt: "Enter courier name",
    trackingPrompt: "Enter tracking number",
    rejectPackagingPrompt: "Enter packaging rejection reason",
    rejectShippingPrompt: "Enter shipping rejection reason",
    reprintLabelPrompt: "Enter label reprint reason",
    updateCourier: "Update Courier",
    updateTrackingNumber: "Update Tracking Number",
    pickSuccess: "Item marked picked.",
    processingHandoverSuccess: "Item handed over to packaging.",
    packagingReceiptConfirmedSuccess: "Packaging receipt confirmed.",
    packagingReceiptRejectedSuccess: "Packaging receipt rejected.",
    packagingStartedSuccess: "Packaging started.",
    packageVerifiedSuccess: "Package check recorded.",
    labelPrintedSuccess: "Shipping label printed.",
    labelReprintedSuccess: "Shipping label reprinted.",
    packagePackedSuccess: "Item marked packed.",
    packagingHandoverSuccess: "Item handed over to shipping.",
    shippingReceiptConfirmedSuccess: "Shipping receipt confirmed.",
    shippingReceiptRejectedSuccess: "Shipping receipt rejected.",
    shippingCompletedSuccess: "Item marked shipped.",
    cancellationHandoverSuccess: "Item handed over to cancellation.",
    cancellationRequested: "Cancellation Requested",
    cancellationRequestedHint: "This item requires handover to the cancellation manager before stock can be resolved.",
    cancelConfirm: "Cancel this item before shipment?",
    outboundTrackingRequired: "Enter a tracking number before marking the item as shipped.",
    orderStatusPrefix: "Order Status",
    paymentStatusPrefix: "Payment Status",
    preShipmentCancellation: "Cancelled Before Shipment",
    customerReturnFlow: "Customer Return",
    inventoryAcceptancePendingCancelHint: "The cancellation manager can now decide whether to restock, mark damaged, or mark lost.",
    cancelledInventoryHint: "Cancelled inventory is handled directly by the cancellation manager in this phase.",
    inventoryAcceptancePendingReturnHint: "Return handling is out of scope in this fulfilment phase.",
    shippingBlockedHint: "Shipping is blocked while this item is in a cancellation lane.",
    failedPaymentBlocked: "Failed-payment orders are visible for review only. They cannot enter fulfillment.",
    emptyQueue: "No orders are waiting in this lane.",
    paymentStates: {
      pending: "Pending",
      paid: "Paid",
      payment_failed: "Payment Failed",
      refund_pending: "Refund Pending",
      partially_refunded: "Partially Refunded",
      refunded: "Refunded",
    },
    metricsPaidOrders: "Paid Orders",
    metricsFailedPayments: "Failed Payments",
    metricsGrossRevenue: "Gross Revenue",
    metricsRefundTotal: "Refund Total",
    metricsSoldItems: "Sold Items",
    metricsCancelledItems: "Cancelled Items",
    metricsSoldByDay: "Sold By Day",
    metricsSoldByMonth: "Sold By Month",
    metricsSoldByQuarter: "Sold By Quarter",
    metricsCancelledByDay: "Cancelled By Day",
    metricsCancelledByMonth: "Cancelled By Month",
    metricsCancelledByQuarter: "Cancelled By Quarter",
    metricsTopSellingProducts: "Top Selling Products",
    metricsTopSellingCategories: "Top Selling Categories",
    metricsTopCancelledProducts: "Top Cancelled Products",
    metricsTopCancelledCategories: "Top Cancelled Categories",
    metricsNoData: "No metrics available yet.",
    states: {
      PLACED: "Placed",
      PARTIALLY_PICKED: "Picking In Progress",
      PICKED: "Picked",
      PARTIALLY_PACKED: "Packaging In Progress",
      PARTIALLY_SHIPPED: "Shipment In Progress",
      PARTIALLY_CANCELLED: "Partially Cancelled",
      CANCELLED: "Cancelled",
      CLOSED: "Closed",
      RESERVED: "Reserved",
      PICKED_FROM_WAREHOUSE: "Picked From Warehouse",
      HANDED_TO_PACKAGING: "Handed To Packaging",
      PACKAGING_RECEIVED: "Packaging Received",
      PACKAGING_IN_PROGRESS: "Packaging In Progress",
      PACKED: "Packed",
      HANDED_TO_SHIPPING: "Handed To Shipping",
      SHIPPING_RECEIVED: "Shipping Received",
      SHIPPING_IN_PROGRESS: "Shipping In Progress",
      SHIPPED: "Shipped",
      DELIVERED: "Delivered",
      CANCELLED_BEFORE_PICKING: "Cancelled Before Picking",
      CANCEL_REQUESTED: "Cancellation Requested",
      HANDED_TO_CANCELLATION: "Handed To Cancellation",
      CANCELLATION_RECEIVED: "Cancellation Received",
      CANCEL_RESTOCKED: "Cancelled And Restocked",
      CANCEL_DAMAGED: "Cancelled As Damaged",
      CANCEL_LOST: "Cancelled As Lost",
      CANCEL_CLOSED: "Cancellation Closed",
      RETURN_REQUESTED: "Return Requested",
      COLLECTION_SCHEDULED: "Collection Scheduled",
      RETURN_IN_TRANSIT: "Return In Transit",
      RETURN_RECEIVED: "Return Received",
      INVENTORY_ACCEPTANCE_PENDING_RETURN: "Inventory Acceptance Pending (Return)",
      REFUND_COMPLETED: "Refund Completed",
      ON_TRACK: "On Track",
      DELAYED: "Delayed",
      VIOLATED: "Violated",
    },
  },
  inventory: {
    title: "Stock",
    summaryTitle: "Inventory Summary",
    dashboardTabsLabel: "Inventory Dashboard",
    overviewTab: "Overview",
    lowStockTab: "Low Stock",
    outOfStockTab: "Out of Stock",
    searchLabel: "Search",
    searchPlaceholder: "Search by SKU, size, title, or slug",
    sortLabel: "Sort",
    sortUpdatedDesc: "Recently updated",
    sortUpdatedAsc: "Oldest updates",
    sortStockAsc: "Lowest stock first",
    sortStockDesc: "Highest stock first",
    sortTitleAsc: "Product A-Z",
    sortTitleDesc: "Product Z-A",
    productLabel: "Product",
    variantLabel: "Variant",
    categoryLabel: "Category",
    statusLabel: "Status",
    updatedAtLabel: "Last updated",
    remainingQuantity: "Remaining",
    stockKeyLabel: "Stock Key",
    sizeLabel: "Size",
    skuCount: "SKUs",
    productsCount: "Products",
    stockDetailsTitle: "Stock Breakdown",
    orderDetailsTitle: "Order Details",
    expandRow: "Expand",
    collapseRow: "Collapse",
    initialQuantity: "Initial",
    currentQuantity: "Current",
    soldQuantity: "Sold",
    reorderLevel: "Reorder Level",
    soldInOrders: "Sold in Orders",
    noSales: "No sales yet",
    filteredSkus: "Filtered SKUs",
    currentUnits: "Current Units",
    soldUnits: "Sold Units",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    lowStockBadge: "Needs attention",
    lowStockHint: "Current stock is at or below the reorder level.",
    lowStockRule: "Low Stock Items: stock greater than 0 and less than 2.",
    outOfStockRule: "Out of Stock Items: stock equal to 0.",
    totalActiveProducts: "Active Products",
    totalActiveVariants: "Active Variants",
    recentUpdatesTitle: "Recently Updated Stock",
    categoryRiskTitle: "Category Stock Risk",
    inventoryExplorerTitle: "Inventory Explorer",
    overviewSubtitle: "Monitor live stock health, then drill into low-stock and out-of-stock variants.",
    riskListSubtitle: "Review every matching variant with search, sorting, and pagination.",
    showingCount: (visible: number, total: number) => `Showing ${visible} of ${total}`,
    viewAllLowStock: "View all low-stock items",
    viewAllOutOfStock: "View all out-of-stock items",
    skuSuffix: "SKU",
    editorTitle: "Update Inventory",
    quantityLabel: "Current quantity",
    reorderLevelLabel: "Reorder level",
    quantityHelp: "Adjust the live sellable quantity for this SKU.",
    reorderLevelHelp: "Flag this SKU when current stock reaches this threshold.",
    saveError: "Enter non-negative numbers for quantity and reorder level.",
    emptyState: "No inventory matches the current filters.",
    noOrderDetails: "No order details for this product.",
    riskEmptyState: "No inventory items match the current stock-risk filters.",
  },
  products: {
    title: "Products",
    categoryLabel: "Category",
    allCategories: "All categories",
    createProduct: "Create Product",
    defaultVariantMissing: "-",
    variants: "Variants",
    publish: "Publish",
    unpublish: "Unpublish",
    headers: [
      "Variant",
      "Title",
      "Slug",
      "Default Variant",
      "Colors",
      "Care",
      "Discount",
      "Featured",
      "Status",
      "Actions",
    ] as const,
    deleteConfirm: (title: string) =>
      `Delete product "${title}"? This will permanently delete product, variants and stock.`,
  },
  reviews: {
    title: "Product Reviews",
    subtitle: "Moderate customer product reviews and keep public ratings trustworthy.",
    filtersTitle: "Filters",
    searchPlaceholder: "Search by product, customer, title, or comment",
    statusAll: "All statuses",
    verifiedAll: "All reviewers",
    verifiedOnly: "Verified buyers",
    unverifiedOnly: "Unverified",
    ratingAll: "All ratings",
    empty: "No reviews match the current filters.",
    loading: "Loading reviews...",
    detailTitle: "Review Detail",
    selectPrompt: "Select a review to inspect verification context and moderate it.",
    verifiedBuyer: "Verified Buyer",
    approve: "Approve",
    reject: "Reject",
    hide: "Hide",
    moderationReason: "Moderation reason",
    moderationNote: "Moderation note",
    moderationSource: "Moderation source",
    moderationSignals: "Moderation signals",
    automatedModeration: "Automated Moderation",
    moderationProvider: "Provider",
    moderationModel: "Model",
    moderationDecision: "Decision",
    moderationCategories: "Flagged categories",
    moderationScores: "Category scores",
    moderationFailure: "Provider fallback",
    moderationCheckedAt: "Checked at",
    verificationContext: "Verification context",
    reviewContent: "Review content",
    customer: "Customer",
    product: "Product",
    rating: "Rating",
    status: "Status",
    created: "Created",
    orderReference: "Verified order",
    productUnavailable: "Unknown product",
  },
} as const;
