export const ADMIN_UI_STRINGS = {
  brand: {
    portalTitle: "Admin Portal",
  },
  shell: {
    notSignedIn: "Not signed in",
    authStatusPrefix: "Auth status:",
    authBootstrapTitle: "Auth bootstrap diagnostic",
    profile: "Profile",
    logout: "Logout",
  },
  login: {
    title: "Admin Login",
    fields: {
      email: "Email",
      password: "Password",
    },
    signIn: "Sign In",
    signingIn: "Signing in...",
    failed: "Login failed",
    localUrlsTitle: "Local URLs",
    localUrlsCopy:
      "The admin menu is permission-based, so it becomes available after a successful sign-in.",
  },
  menu: {
    profile: "Profile",
    sessions: "Sessions",
    users: "Users",
    roles: "Roles",
    permissions: "Permissions",
    categories: "Categories",
    products: "Products",
    inventory: "Inventory",
    systemHealth: "System Health",
    audit: "Audit",
  },
  common: {
    refresh: "Refresh",
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    action: "Action",
    status: "Status",
    loadingProducts: "Loading products...",
    noImage: "no image",
    yes: "Yes",
    no: "No",
  },
  localUrls: {
    adminPortal: "Admin portal",
    gatewayApi: "Gateway API",
    gatewayHealth: "Gateway health",
    storefront: "Customer storefront",
  },
  health: {
    title: "System Health",
    up: "UP",
    down: "DOWN",
    services: {
      gateway: "Gateway",
      auth: "Auth",
      catalog: "Catalog",
      product: "Product",
    },
  },
  categories: {
    title: "Categories",
    createCategory: "Create Category",
    table: {
      name: "Name",
      slug: "Slug",
      sort: "Sort",
      status: "Status",
      action: "Action",
    },
    tree: {
      collapse: "Collapse",
      expand: "Expand",
    },
  },
  inventory: {
    title: "Stock",
    headers: ["Stock Key", "Variant", "Size", "Quantity", "Reorder Level", "Action"] as const,
    prompts: {
      quantity: "Quantity",
      reorderLevel: "Reorder level",
    },
  },
  products: {
    title: "Products",
    categoryLabel: "Category",
    allCategories: "All categories",
    createProduct: "Create Product",
    defaultVariantMissing: "-",
    variants: "Variants",
    publish: "Publish",
    unpublish: "Unpublish",
    headers: [
      "Variant",
      "Title",
      "Slug",
      "Default Variant",
      "Colors",
      "Care",
      "Discount",
      "Featured",
      "Status",
      "Actions",
    ] as const,
    deleteConfirm: (title: string) =>
      `Delete product "${title}"? This will permanently delete product, variants and stock.`,
  },
} as const;
